package com.sentinel.hemo_grid.common.exception;

public enum ErrorCode {
	VALIDATION_FAILED,
	UNAUTHORIZED,
	FORBIDDEN,
	RESOURCE_NOT_FOUND,
	INVALID_REQUEST_STATUS,
	INVALID_STATUS_TRANSITION,
	INSUFFICIENT_INVENTORY,
	PROVIDER_NOT_SELECTED,
	ORGANIZATION_INACTIVE,
	ORGANIZATION_TYPE_MISMATCH,
	REQUEST_ALREADY_FINALIZED,
	INTERNAL_ERROR
}
